name: CI

on: [ "push", "pull_request" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x

      - name: Run the Cake script
        uses: cake-build/cake-action@v1
        with:
          verbosity: Diagnostic

      - uses: actions/upload-artifact@v3
        with:
          name: BepInEx.AutoPlugin.nupkg
          path: BepInEx.AutoPlugin/bin/Release/*.nupkg

      - name: Push NuGet package
        if: github.ref_type == 'tag'
        run: |
          dotnet nuget push BepInEx.AutoPlugin/bin/Release/*.nupkg --source ${{ secrets.BEPIN_DEV_NUGET_SOURCE }} --api-key ${{ secrets.BEPIN_DEV_NUGET_KEY }}
